[package]
name = "juke"
version = "0.1.0"
authors = ["dbr <dbr.onix@gmail.com>"]
edition = "2018"

[dependencies]
rspotify = "0.2.5"
failure = "0.1"
rouille = "1"
rand = "0.6"
serde = "*"
serde_json = "*"
serde_derive = "*"

[dev-dependencies]
reqwest = "0.9.5"
